name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: myoro_api_test
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        ports:
          - 5632:5432
        options: >-
          --health-cmd "pg_isready -U sail -d myoro_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install

      - name: Start Sail
        run: |
          cp .env .env.testing
          echo "DB_HOST=pgsql" >> .env.testing
          echo "DB_DATABASE=myoro_api_test" >> .env.testing
          echo "DB_USERNAME=sail" >> .env.testing
          echo "DB_PASSWORD=password" >> .env.testing
          ./vendor/bin/sail up -d

      - name: Run Migrations
        run: ./vendor/bin/sail artisan migrate --env=testing --force

      - name: Run Tests
        run: ./vendor/bin/sail artisan test --coverage
