name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.1'

      - name: Set up Docker
        uses: docker/setup-docker-action@v1

      - name: Install dependencies
        run: composer install

      - name: Fix permissions
        run: sudo chmod -R 777 vendor/pestphp/pest/.temp

      - name: Start Sail
        run: ./vendor/bin/sail up -d --build && ./vendor/bin/sail artisan config:clear

      - name: Run tests (fails if any test fails or if code coverage isn't 100%)
        run: ./vendor/bin/sail artisan test --coverage
