name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install

      - name: Start Sail
        run: |
          ./vendor/bin/sail down
          ./vendor/bin/sail up -d --remove-orphans

      - name: Wait for PostgreSQL
        run: |
          ./vendor/bin/sail exec pgsql sh -c 'until pg_isready -U sail -d myoro_api_test; do sleep 1; done'

      - name: Fix Storage Permissions
        run: ./vendor/bin/sail exec laravel.test chmod -R 777 storage/logs

      - name: Run Migrations
        run: ./vendor/bin/sail artisan migrate --env=testing --force

      - name: Run Tests with Coverage (only passes if all tests pass with 100% code coverage)
        run: ./vendor/bin/sail exec laravel.test env XDEBUG_MODE=coverage php artisan test --coverage
