name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.1'

      - name: Set up Docker
        uses: docker/setup-docker-action@v1

      - name: Install dependencies
        run: composer install

      - name: Fix permissions
        run: |
          mkdir -p /var/www/html/storage/logs vendor/pestphp/pest/.temp
          sudo chmod -R 777 /var/www/html/storage/logs vendor/pestphp/pest/.temp

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Start Sail
        run: |
          ./vendor/bin/sail up -d --build
          ./vendor/bin/sail artisan config:clear

      - name: Run tests (fails if any test fails or if code coverage isn't 100%)
        run: ./vendor/bin/sail artisan test --coverage
